import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  char,
  date,
  datetime,
  decimal,
  index,
  int,
  json,
  mysqlTable,
  primaryKey,
  text,
  uniqueIndex,
  varchar,
} from "drizzle-orm/mysql-core";

export const orderIntents = mysqlTable(
  "order_intents",
  {
    id: char("id", { length: 36 }).primaryKey().notNull(),
    brokerAccountId: char("broker_account_id", { length: 36 }).notNull(),
    instrumentId: char("instrument_id", { length: 36 }).notNull(),
    signalId: char("signal_id", { length: 36 }),
    candidateId: char("candidate_id", { length: 36 }),
    intentKey: varchar("intent_key", { length: 191 }).notNull(),
    ruleKey: varchar("rule_key", { length: 100 }).notNull(),
    source: varchar("source", { length: 40 }).notNull(),
    side: varchar("side", { length: 10 }).notNull(),
    quantity: decimal("quantity", { precision: 28, scale: 8, mode: "string" }).notNull(),
    referencePrice: decimal("reference_price", { precision: 28, scale: 8, mode: "string" }),
    orderType: varchar("order_type", { length: 20 }).notNull().default("MARKET"),
    tradingMode: varchar("trading_mode", { length: 20 }).notNull(),
    status: varchar("status", { length: 30 }).notNull(),
    reason: varchar("reason", { length: 1000 }),
    createdAt: datetime("created_at", { fsp: 6, mode: "string" }).notNull().default(sql`CURRENT_TIMESTAMP(6)`),
    updatedAt: datetime("updated_at", { fsp: 6, mode: "string" }).notNull().default(sql`CURRENT_TIMESTAMP(6)`).$onUpdate(() => sql`CURRENT_TIMESTAMP(6)`),
    completedAt: datetime("completed_at", { fsp: 6, mode: "string" }),
  },
  (table) => [
    index("fk_order_intents_candidate").on(table.candidateId),
    index("fk_order_intents_signal").on(table.signalId),
    index("ix_order_intents_account_time").on(table.brokerAccountId, table.createdAt),
    index("ix_order_intents_instrument_time").on(table.instrumentId, table.createdAt),
    index("ix_order_intents_status").on(table.status),
    uniqueIndex("uq_order_intents_key").on(table.brokerAccountId, table.intentKey),
  ],
);

export const orders = mysqlTable(
  "orders",
  {
    id: char("id", { length: 36 }).primaryKey().notNull(),
    brokerAccountId: char("broker_account_id", { length: 36 }).notNull(),
    instrumentId: char("instrument_id", { length: 36 }).notNull(),
    intentId: char("intent_id", { length: 36 }),
    localOrderId: varchar("local_order_id", { length: 191 }).notNull(),
    brokerOrderNo: varchar("broker_order_no", { length: 80 }),
    brokerOrderDate: date("broker_order_date", { mode: "string" }),
    brokerOrgNo: varchar("broker_org_no", { length: 80 }),
    side: varchar("side", { length: 10 }).notNull(),
    orderType: varchar("order_type", { length: 20 }).notNull(),
    requestedQty: decimal("requested_qty", { precision: 28, scale: 8, mode: "string" }).notNull(),
    requestedPrice: decimal("requested_price", { precision: 28, scale: 8, mode: "string" }),
    filledQty: decimal("filled_qty", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    remainingQty: decimal("remaining_qty", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    averageFillPrice: decimal("average_fill_price", { precision: 28, scale: 8, mode: "string" }),
    currency: char("currency", { length: 3 }).notNull(),
    status: varchar("status", { length: 30 }).notNull(),
    source: varchar("source", { length: 40 }),
    sourceId: varchar("source_id", { length: 191 }),
    ruleKey: varchar("rule_key", { length: 100 }).notNull(),
    reason: varchar("reason", { length: 1000 }),
    brokerCode: varchar("broker_code", { length: 80 }),
    brokerMessage: varchar("broker_message", { length: 1000 }),
    submittedAt: datetime("submitted_at", { fsp: 6, mode: "string" }),
    acceptedAt: datetime("accepted_at", { fsp: 6, mode: "string" }),
    completedAt: datetime("completed_at", { fsp: 6, mode: "string" }),
    createdAt: datetime("created_at", { fsp: 6, mode: "string" }).notNull().default(sql`CURRENT_TIMESTAMP(6)`),
    updatedAt: datetime("updated_at", { fsp: 6, mode: "string" }).notNull().default(sql`CURRENT_TIMESTAMP(6)`).$onUpdate(() => sql`CURRENT_TIMESTAMP(6)`),
  },
  (table) => [
    index("ix_orders_account_status_time").on(table.brokerAccountId, table.status, table.createdAt),
    index("ix_orders_broker_no").on(table.brokerOrderNo),
    index("ix_orders_instrument_status").on(table.instrumentId, table.status),
    index("ix_orders_intent").on(table.intentId),
    uniqueIndex("uq_orders_broker").on(table.brokerAccountId, table.brokerOrderDate, table.brokerOrderNo),
    uniqueIndex("uq_orders_local").on(table.brokerAccountId, table.localOrderId),
  ],
);

export const orderEvents = mysqlTable(
  "order_events",
  {
    id: char("id", { length: 36 }).primaryKey().notNull(),
    orderId: char("order_id", { length: 36 }).notNull(),
    eventType: varchar("event_type", { length: 40 }).notNull(),
    previousStatus: varchar("previous_status", { length: 30 }),
    newStatus: varchar("new_status", { length: 30 }),
    brokerCode: varchar("broker_code", { length: 80 }),
    brokerMessage: varchar("broker_message", { length: 1000 }),
    metadataJson: json("metadata_json"),
    eventAt: datetime("event_at", { fsp: 6, mode: "string" }).notNull(),
    createdAt: datetime("created_at", { fsp: 6, mode: "string" }).notNull().default(sql`CURRENT_TIMESTAMP(6)`),
  },
  (table) => [
    index("ix_order_events_order_time").on(table.orderId, table.eventAt),
    index("ix_order_events_type_time").on(table.eventType, table.eventAt),
  ],
);

export const executions = mysqlTable(
  "executions",
  {
    id: char("id", { length: 36 }).primaryKey().notNull(),
    brokerAccountId: char("broker_account_id", { length: 36 }).notNull(),
    orderId: char("order_id", { length: 36 }).notNull(),
    instrumentId: char("instrument_id", { length: 36 }).notNull(),
    tradeId: char("trade_id", { length: 36 }),
    executionKey: varchar("execution_key", { length: 191 }).notNull(),
    brokerExecutionId: varchar("broker_execution_id", { length: 120 }),
    brokerOrderNo: varchar("broker_order_no", { length: 80 }),
    side: varchar("side", { length: 10 }).notNull(),
    quantity: decimal("quantity", { precision: 28, scale: 8, mode: "string" }).notNull(),
    price: decimal("price", { precision: 28, scale: 8, mode: "string" }).notNull(),
    grossAmount: decimal("gross_amount", { precision: 28, scale: 8, mode: "string" }).notNull(),
    commission: decimal("commission", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    tax: decimal("tax", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    otherFee: decimal("other_fee", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    realizedPnl: decimal("realized_pnl", { precision: 28, scale: 8, mode: "string" }),
    currency: char("currency", { length: 3 }).notNull(),
    fxRateToBase: decimal("fx_rate_to_base", { precision: 28, scale: 8, mode: "string" }),
    baseGrossAmount: decimal("base_gross_amount", { precision: 28, scale: 8, mode: "string" }),
    executedAt: datetime("executed_at", { fsp: 6, mode: "string" }).notNull(),
    brokerPayload: json("broker_payload"),
    createdAt: datetime("created_at", { fsp: 6, mode: "string" }).notNull().default(sql`CURRENT_TIMESTAMP(6)`),
  },
  (table) => [
    index("ix_executions_broker_order_no").on(table.brokerOrderNo),
    index("ix_executions_instrument_time").on(table.instrumentId, table.executedAt),
    index("ix_executions_order").on(table.orderId, table.executedAt),
    index("ix_executions_trade").on(table.tradeId),
    uniqueIndex("uq_executions_key").on(table.brokerAccountId, table.executionKey),
  ],
);

export const positions = mysqlTable(
  "positions",
  {
    id: char("id", { length: 36 }).primaryKey().notNull(),
    brokerAccountId: char("broker_account_id", { length: 36 }).notNull(),
    instrumentId: char("instrument_id", { length: 36 }).notNull(),
    ruleScope: varchar("rule_scope", { length: 100 }).notNull(),
    quantity: decimal("quantity", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    availableQuantity: decimal("available_quantity", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    averagePrice: decimal("average_price", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    totalCost: decimal("total_cost", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    marketPrice: decimal("market_price", { precision: 28, scale: 8, mode: "string" }),
    marketValue: decimal("market_value", { precision: 28, scale: 8, mode: "string" }),
    unrealizedPnl: decimal("unrealized_pnl", { precision: 28, scale: 8, mode: "string" }),
    unrealizedReturnPct: decimal("unrealized_return_pct", { precision: 18, scale: 8, mode: "string" }),
    currency: char("currency", { length: 3 }).notNull(),
    provenance: varchar("provenance", { length: 40 }).notNull().default("RUNTIME"),
    lastPriceAt: datetime("last_price_at", { fsp: 6, mode: "string" }),
    lastReconciledAt: datetime("last_reconciled_at", { fsp: 6, mode: "string" }),
    createdAt: datetime("created_at", { fsp: 6, mode: "string" }).notNull().default(sql`CURRENT_TIMESTAMP(6)`),
    updatedAt: datetime("updated_at", { fsp: 6, mode: "string" }).notNull().default(sql`CURRENT_TIMESTAMP(6)`).$onUpdate(() => sql`CURRENT_TIMESTAMP(6)`),
  },
  (table) => [
    index("ix_positions_account").on(table.brokerAccountId),
    index("ix_positions_instrument").on(table.instrumentId),
    uniqueIndex("uq_positions_scope").on(table.brokerAccountId, table.instrumentId, table.ruleScope),
  ],
);

export const trades = mysqlTable(
  "trades",
  {
    id: char("id", { length: 36 }).primaryKey().notNull(),
    brokerAccountId: char("broker_account_id", { length: 36 }).notNull(),
    instrumentId: char("instrument_id", { length: 36 }).notNull(),
    ruleScope: varchar("rule_scope", { length: 100 }).notNull(),
    source: varchar("source", { length: 40 }).notNull(),
    status: varchar("status", { length: 30 }).notNull(),
    totalBuyQty: decimal("total_buy_qty", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    totalSellQty: decimal("total_sell_qty", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    totalBuyAmount: decimal("total_buy_amount", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    totalSellAmount: decimal("total_sell_amount", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    averageBuyPrice: decimal("average_buy_price", { precision: 28, scale: 8, mode: "string" }),
    averageSellPrice: decimal("average_sell_price", { precision: 28, scale: 8, mode: "string" }),
    totalCommission: decimal("total_commission", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    totalTax: decimal("total_tax", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    totalOtherFee: decimal("total_other_fee", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    realizedPnl: decimal("realized_pnl", { precision: 28, scale: 8, mode: "string" }).notNull().default("0.00000000"),
    realizedReturnPct: decimal("realized_return_pct", { precision: 18, scale: 8, mode: "string" }),
    currency: char("currency", { length: 3 }).notNull(),
    openedAt: datetime("opened_at", { fsp: 6, mode: "string" }).notNull(),
    closedAt: datetime("closed_at", { fsp: 6, mode: "string" }),
    createdAt: datetime("created_at", { fsp: 6, mode: "string" }).notNull().default(sql`CURRENT_TIMESTAMP(6)`),
    updatedAt: datetime("updated_at", { fsp: 6, mode: "string" }).notNull().default(sql`CURRENT_TIMESTAMP(6)`).$onUpdate(() => sql`CURRENT_TIMESTAMP(6)`),
  },
  (table) => [
    index("ix_trades_account_status_time").on(table.brokerAccountId, table.status, table.openedAt),
    index("ix_trades_instrument_time").on(table.instrumentId, table.openedAt),
  ],
);
