/** Objects already present on production RDS `auto_trading`. Do not DROP or recreate. */
export const EXPECTED_TABLES = [
  "account_snapshots",
  "ai_recommendations",
  "audit_logs",
  "auth_sessions",
  "auto_conditions",
  "broker_accounts",
  "broker_credential_refs",
  "broker_secret_payloads",
  "cash_balance_snapshots",
  "daily_performance",
  "dca_plans",
  "equity_snapshots",
  "executions",
  "fx_rate_snapshots",
  "instrument_aliases",
  "instrument_sync_runs",
  "instruments",
  "migration_runs",
  "notifications",
  "order_events",
  "order_intents",
  "orders",
  "positions",
  "reconciliation_items",
  "reconciliation_runs",
  "risk_decisions",
  "risk_limits",
  "rule_allocations",
  "trade_signals",
  "trades",
  "trading_account_state",
  "trading_candidates",
  "trading_rules",
  "user_consents",
  "user_settings",
  "users",
  "watchlist_items",
  "watchlists",
] as const;

export const EXPECTED_VIEWS = ["v_buy_history"] as const;

export const EXPECTED_OBJECTS = [...EXPECTED_TABLES, ...EXPECTED_VIEWS] as const;
